name: Temporary SSH (tmate - auto)

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Keep alive for 6 hours
        run: |
          echo "tmate session is running..."
          sleep 21600
