name: Temporary Shell (tunshell)

on:
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Start Tunshell
        run: |
          curl -sSf https://lets.tunshell.com/init.sh | sh -s -- \
            T \
            Hjwh2dWBc4N7cTZzxmpcoF \
            MDIy5nlUtbnA77Y7yuaocO \
            eu.relay.tunshell.com

      - name: Keep alive
        run: sleep 21600
